-- 011_bracket.sql — the double-elimination bracket.
--
-- Run in the Supabase SQL editor AFTER 010. Safe to re-run.
--
-- One table. Every match of the whole tournament is written the moment the
-- bracket is generated, with empty team slots that name where their occupants
-- come from — see shared/bracket.cjs. Advancing a team is then an UPDATE of a
-- row that already exists, never an INSERT of a round that didn't.
--
-- That is the whole design decision. Generating rounds as they become needed is
-- where double-elimination implementations go wrong: the losers bracket's shape
-- depends on results that haven't happened, so the code that builds it is
-- scattered across every result handler and nobody can look at a bracket and
-- say whether it is right. Here the shape is decided once, by a pure function
-- with fifty thousand simulated tournaments behind it, and this table is where
-- that function's output is kept.

create table if not exists matches (
  id             uuid primary key default gen_random_uuid(),
  tournament_id  uuid not null references tournaments(id) on delete cascade,

  -- 'W3-0', 'L4-1', 'GF1-0'. Generated by shared/bracket.cjs and stable for a
  -- given bracket size, which is what lets slot_a/slot_b below refer to other
  -- matches without needing their uuids to exist first.
  key            text not null,

  bracket        text not null,
  round          int  not null,
  idx            int  not null,

  -- Where each side comes from:
  --   {"type":"seed","seed":3}       the 3rd seed starts here
  --   {"type":"winner","of":"W1-2"}  whoever wins that match
  --   {"type":"loser","of":"W1-2"}   whoever loses it
  --
  -- Stored rather than recomputed so a result can be applied by reading this
  -- table alone. The alternative is regenerating the skeleton on every result
  -- to find out where the loser goes, which works right up until the team count
  -- changes and every historical match starts answering a different question.
  slot_a         jsonb not null,
  slot_b         jsonb not null,

  -- Deliberately NOT foreign keys, for two reasons that both matter:
  --
  --   · three references to `teams` from one table would give PostgREST three
  --     relationships to choose between and break every embed — the same trap
  --     006 documents. Teams are stitched in JS instead.
  --   · a completed match is a record of what happened. ON DELETE CASCADE would
  --     erase results and SET NULL would quietly rewrite them. Deleting a team
  --     that is in a bracket is refused in backend/teams.js instead, which can
  --     say why.
  team_a_id      uuid,
  team_b_id      uuid,
  winner_team_id uuid,
  loser_team_id  uuid,

  -- What KIND of match this is, structurally. Set once at generation.
  --   'match'    both sides real — somebody plays it
  --   'walkover' one side is an empty chair; the other advances for free
  --   'void'     both sides empty — it does not happen at all
  kind           text not null default 'match',
  -- For a walkover, which slot advances.
  advances       text,

  -- Where it is in its life. Separate from `kind` on purpose: a walkover is
  -- structurally a walkover forever, and separately it is pending until the
  -- team that walks over is known.
  --   'pending'  waiting on the teams
  --   'ready'    both teams known, waiting on a result
  --   'complete' decided
  status         text not null default 'pending',

  -- The reset game. Exists from generation and is played only if the losers
  -- bracket team wins the first grand final.
  is_reset       boolean not null default false,

  scheduled_at   timestamptz,
  decided_at     timestamptz,
  decided_by     text,

  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

do $$ begin
  -- The key IS the identity of a match within a tournament. Without this, a
  -- second generate would silently double every round rather than fail.
  if not exists (select 1 from pg_constraint where conname = 'matches_key_unique') then
    alter table matches add constraint matches_key_unique unique (tournament_id, key);
  end if;

  if not exists (select 1 from pg_constraint where conname = 'matches_bracket_valid') then
    alter table matches add constraint matches_bracket_valid
      check (bracket in ('W', 'L', 'GF'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'matches_kind_valid') then
    alter table matches add constraint matches_kind_valid
      check (kind in ('match', 'walkover', 'void'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'matches_status_valid') then
    alter table matches add constraint matches_status_valid
      check (status in ('pending', 'ready', 'complete'));
  end if;

  -- A completed match has a winner, and an undecided one does not. Without
  -- this, a half-applied result leaves a match that reads as finished with
  -- nobody having won it, and the bracket advances nothing while looking done.
  if not exists (select 1 from pg_constraint where conname = 'matches_winner_iff_complete') then
    alter table matches add constraint matches_winner_iff_complete
      check ((status = 'complete') = (winner_team_id is not null));
  end if;

  -- The winner cannot also be the loser, and a team cannot play itself. Cheap
  -- to state, and the failure it catches — a slot written twice by a bad
  -- advance — otherwise produces a match that looks perfectly normal.
  if not exists (select 1 from pg_constraint where conname = 'matches_two_sides') then
    alter table matches add constraint matches_two_sides
      check (team_a_id is null or team_b_id is null or team_a_id <> team_b_id);
  end if;
end $$;

create index if not exists matches_tournament_idx
  on matches (tournament_id, bracket, round, idx);

-- "What can be played now" — the query the bracket page and the organizer's
-- result form both start from.
create index if not exists matches_ready_idx
  on matches (tournament_id, status) where status = 'ready';

drop trigger if exists matches_touch on matches;
create trigger matches_touch
  before update on matches
  for each row execute function touch_updated_at();

-- Check — the shape of the generated bracket:
--   select bracket, round, count(*) filter (where kind = 'match')     as real,
--                          count(*) filter (where kind = 'walkover')  as byes,
--                          count(*) filter (where kind = 'void')      as absent
--     from matches group by bracket, round order by bracket, round;
--
-- And the path through it:
--   select key, bracket, round, status, team_a_id, team_b_id, winner_team_id
--     from matches order by bracket, round, idx;
